### ISSUE TITLE
GraphQL backend

### ISSUE THREAD

**Issue by pm5** [SenseTW/sensetw#106]
This is meta-issue to keep track of tasks related to the new backend:

- [ ] Write a GraphQL backend to replace Graphcool.
- [ ] #59 Deploy
- [ ] #62 Add Hypothesis-compatible API to for Annotation
- [ ] #98 Add Hypothesis-compatible API to for Group
- [ ] #90 Add Hypothesis-compatible API to for User

**Comment by pm5** [comment]
Replaced by #119
