### ISSUE TITLE
Full history: research

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#253]
# Job Story
When I re-enter the map,
I want to see what has been changed on the map,
So that I can respond to those new changes with my opinion

# Success Criteria
### Showing {Who} {edit} {what} at {what time} on a Card, a box and a Map
- Edits on Card:
  - Add {text} in {summary} and {description}, {tag}, {stakeholders}, {said_by}, {source_link}, {source_title}
  - Delete {text} in {summary} and {description}, {tag}, {stakeholders}, {said_by}, {source_link}, {source_title}
  - Change Card type from {} to {}
- Edits on Box
  - Add {text}, {tag}
  - Delete {text}, {tag}, {stakeholders}, {said_by}, {source_link}, {source_title}
  - Change Box type from {} to {}
- Edits on Map
  - Add/Delete {CARD}, {BOX}
  - Add / Delete {EDGE} between {} and {}
  - Add/Eject {CARD} into / out of {BOX}
  - Add/Delete {text} in {description}, {tag} in Map details
  - Change Map name from {} to {}

# To be discuss
1. Only Map owner can revert to one version
2. Only card/box creator can delete that card/box

### How to solve conflicts
Possible solutions:
1. Overwrite
2. Locked card edit when one is editing (like wiki)

# Out of scope

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1212905

**Comment by pm5** [comment]
## Implementation plan

- [ ] Move input validation from database to application code.
- [ ] Build history data structure.
- [ ] Rewrite all write operations into transactions containing validation, write to history, write to db.
