### ISSUE TITLE
BE: Full History

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#265]
# Job Story
When I re-enter the map,
I want to see what has been changed on the map,
So that I can respond to those new changes with my opinion

# UI (developing)
https://github.com/SenseTW/sensetw/issues/263
https://zpl.io/2jwKwWr

# Success Criteria
### Showing {Who} {edit} {what} at {what time} on a Card, a box and a Map
- Edits on Card:
  - Created/ archived/ deleted  by {who} at {time}
  - Added to the map by {who} at {time}
  - {who} changed the summary {} from {} at {time}
  - {who} edited the {description}/ {tag}/ {stakeholders}/ {said_by}/ {source_link}/ {source_title} at {time}
  -  {who} changed Card type from {} to {} at {time}
  -  {who} linked/unlinked this Card to {} at {time}
  -  Added in / ejected out of {Box title} by {who} at {time}

- Edits on Box
  -  Created/ deleted by {who} at {time}
  - {who} changed the Box Title {} from {} at {time}
  - {who} edited  {tag}, {summary} at {time}
  - {who} changed Box type from {} to {} at {time}
  -  {who} linked/unlinked this Box to {} at {time}
  -  {who} added / ejected {Card Summary} out of a this Box at {time}

- Edits on Map
  - Created by {who} at {time}
  - {who} added/deleted {CARD}, {BOX}
  - {who} changed Card Summary "{CARD summary}"/ Box Title "{Box title}" from "{CARD summary}"/ "{Box title}". 
  - {who} edited {description}/ {tag}/ {stakeholders}/ {said_by}/ {source_link}/ {source_title} in Card "{summary}" at {time}
  - {who} edited {tag}, {summary} in Box "{Box title}" at {time}.
  - {who} added / deleted {EDGE} between {} and {}
  - {who} added/ejected Card "{summary}" into / out of Box "{title}".
  - {who} edited {description}, {tag} in Map Details
  - {who} changed Map Name from {} to {}

# To be discuss
1. Only Map owner can revert to one version
2. Only card/box creator can delete that card/box

### How to solve conflicts
Possible solutions:
1. Overwrite
2. Locked card edit when one is editing (like wiki)

# Out of scope

- CRDT
- Transaction queue

# Implementation plan

Based on the research done in https://github.com/SenseTW/sensetw/issues/253

-    Add Transaction types in backend code.
-    Move input validation from database to application code.
-    Build history data structure.
-    Rewrite all write operations into transactions containing validation, write to history, write to db.
-    Build history view

**Comment by aelcenganda** [comment]
UI sync 結論

Conflict:

1. 以新的寫入為準，若已經被刪除會跳通知，告知在 inbox 裡還可以找到。
2. 系統寫入只會去改掉真的有修改的欄位。
3. 刪除：要 card creator 、 box creator 、Map owner 才能刪除。可以刪的人 toolbar 再跳出來。

**Comment by aelcenganda** [comment]
@pm5 我更新了 spec，主要是之前的 spec 沒有每條都寫 {who} 改的。

**Comment by aelcenganda** [comment]
剛剛 sync 的結論是，需要再查一下物件被加入 Box、加上 edge 的 full history 要怎麼做。提醒一下物件會有 Card, Box, Edge。（接下來 edge 要物件化了）

然後顯示的時候會舊的跟新的並陳，只有欄位超過 20 字的才會打開下一層去 diff。

**Comment by pm5** [comment]
# Plan

1. [ ] Build a transaction layer in backend code.
2. [ ] Add history data structure.
3. [ ] Add history logic in transactions.
4. [ ] Add API to query history.
5. [ ] (Frontend) add history displays.

**Comment by aelcenganda** [comment]
周一討論小結：


卡片分為在 inbox 的本體和加到 map 上的分身（物件）。

卡片的本體（點擊 inbox）的 history: 就是只顯示編輯內容的改變，然後會提供分身連結。點擊連結後，會跳到選取分身的 inspector。
分身的 History: 就是編輯內容改變、跟 map 上操作互動，與其他分身連結。
=> 凱蘭也要出圖（明天 sync 再討論一下）

在 Map history 的部份
   - 本體改變的紀錄（更改欄位內容）：點擊 CARD 會有 dropdown 給出條列式的連結，點擊 url 畫面跳到 map 上面的位置，若在 Box 中也會打開 Box 跳到該張卡片。
。（凱蘭要出圖，凱西前端要從 API 給的 id 反查對應的 url）若是沒有加到Map 上，則不給連結（本體目前沒有url）
  - 分身改變的紀錄（加 edge、加入退出BOX）點擊 url 畫面跳到 map 上面的位置，若在 Box 中也會打開 Box 跳到該張卡片。

### 需要另外開 issue 的部份
1. 原本在 map 上的卡片連結，可以在被加入 Box 之後用原本的連結還能打開 Box 跳到卡片上嗎？（目前的連結會是 Map-Box-Card，卡片被加進 Box 之後 url 會換)
2. Inbox 本體也有 link? => 這樣需要設計顯示 inbox 連過去的樣子，可能會是 filter 後單張的顯示結果。
3. 為了達到使用者可以看到同一張卡不同分身在map 上的位置，需要設計 search on map 的顯示與操作 and search in Inbox。

**Comment by aelcenganda** [comment]
周一討論小結：


卡片分為在 inbox 的本體和加到 map 上的分身（物件）。

卡片的本體（點擊 inbox）的 history: 就是只顯示編輯內容的改變，然後會提供分身連結。點擊連結後，會跳到選取分身的 inspector。
分身的 History: 就是編輯內容改變、跟 map 上操作互動，與其他分身連結。
=> 凱蘭也要出圖（明天 sync 再討論一下）

在 Map history 的部份
   - 本體改變的紀錄（更改欄位內容）：點擊 CARD 會有 dropdown 給出條列式的連結，點擊 url 畫面跳到 map 上面的位置，若在 Box 中也會打開 Box 跳到該張卡片。
。（凱蘭要出圖，凱西前端要從 API 給的 id 反查對應的 url）若是沒有加到Map 上，則不給連結（本體目前沒有url）
  - 分身改變的紀錄（加 edge、加入退出BOX）點擊 url 畫面跳到 map 上面的位置，若在 Box 中也會打開 Box 跳到該張卡片。

### 需要另外開 issue 的部份
1. 原本在 map 上的卡片連結，可以在被加入 Box 之後用原本的連結還能打開 Box 跳到卡片上嗎？（目前的連結會是 Map-Box-Card，卡片被加進 Box 之後 url 會換)
2. Inbox 本體也有 link? => 這樣需要設計顯示 inbox 連過去的樣子，可能會是 filter 後單張的顯示結果。
3. 為了達到使用者可以看到同一張卡不同分身在map 上的位置，需要設計 search on map 的顯示與操作 and search in Inbox。

**Comment by aelcenganda** [comment]
寫清楚給 pm5 的 spec：

### Card in Inbox：
顯示本體被編修欄位的紀錄，不記錄 edge 和 box。

- Created/ archived/ deleted by {who} at {time}
- Added to the map by {who} at {time}
- {who} changed the summary {} from {} at {time}
- {who} edited the {description}/ {tag}/ {stakeholders}/ {said_by}/ {source_link}/ {source_title} at {time}
- {who} changed Card type from {} to {} at {time}

### Card on Map
顯示本體被編修欄位的紀錄：

- Created/ archived/ deleted by {who} at {time}
- Added to the map by {who} at {time}
- {who} changed the summary {} from {} at {time}
- {who} edited the {description}/ {tag}/ {stakeholders}/ {said_by}/ {source_link}/ {source_title} at {time}
- {who} changed Card type from {} to {} at {time}

該分身物件 edge 與 Box的關係。

- {who} linked/unlinked this Card to {} at {time}
- Added in / ejected out of {Box title} by {who} at {time}

### Map History
1. 本體被編修欄位的紀錄，沒有超連結（想一想還是覺得很怪，之後可能還是要有 inbox 裡面本體卡的 link，現在先不處理）

- {who} added/deleted {CARD} from Map
- {who} changed Card Summary "{CARD summary}" from "{CARD summary}".
- {who} edited {description}/ {tag}/ {stakeholders}/ {said_by}/ {source_link}/ {source_title} in Card "{summary}" at {time}

2. 分身被操作的紀錄，每個在 map 上的物件要超連結到 map 上的 url。

- {who} added / deleted {EDGE} between {} and {}
- {who} added/ejected Card "{summary}" into / out of Box "{title}".

**Comment by pm5** [comment]
底層的 transaction 進 master 了。接下來要寫 transaction -> history 的邏輯與 history API，還有把 frontend 每個 GraphQL request 都加上 user info。

**Comment by pm5** [comment]
在 history branch 可以測試了：

1. 在 https://history.staging.sense.tw 修改一些東西
2. 在 https://history.staging.api.sense.tw/graphql 可以 query `AllHistories` 查詢修改歷史

GraphQL 範例：

```
query AllHistory($id: ID!) {
  allHistories(filter: { map: { id: $id }, historyType: MAP }, first: 5) {
    id, historyType, createdAt,
    user { id }, map { id }, card { id }, object { id }
    changes { changeType }
  }
}
```

Variable: `{"id":"1dbab857-942d-41d0-baa1-82fa70b0d773"}`

**Comment by pm5** [comment]
有 3 個 db migration，看要 code review 以後再 merge 還是測試完可以就 merge？

**Comment by pm5** [comment]
Closed by #347
