### ISSUE TITLE
FE: 易用性 enhancement (meta)

### ISSUE THREAD

**Issue by aelcenganda** [SenseTW/sensetw#291]
# via.sense.tw 改善（9/27 UI 出圖）
- [x] 步驟流程圖（換掉榕樹） @kanail @caasi(0.25) UI: #231
- [x] 按鈕換成英文 @caasi(0.25) @ael 要給字

# Map editor （9/27 UI 出圖）
- [x] Delete Map & Box 確認刪除訊息 @kanail @caasi(1) UI: #230 

# Other
- [x] Dashboard: click map name to enter a map @caasi #248 
- [x] not logged-in users can’t drag objects @caasi(0.5) #277 
- [x] 縮放顯示百分比（不用 new layout） @caasi

**Comment by aelcenganda** [comment]
via.sense.tw 英文文字：

placeholder:
Paste a link to make some notes on it

btn:
Go!

placeholder:
select a file

btn:
Upload PDF and comment!

**Comment by caasi** [comment]
> placeholder:
> select a file

這段文字是瀏覽器給的，我無法修改。

另外網頁的 title 要換嗎？現在還是「榕樹下」。

**Comment by caasi** [comment]
![2018-10-04 15 44 36](https://user-images.githubusercontent.com/1164470/46459773-6e355b80-c7ec-11e8-81f3-ecbcc340515d.png)
