### ISSUE TITLE
工具 Growth plan before g0v Summit

### ISSUE THREAD

**Issue by aelcenganda** [SenseTW/sensetw#295]
## Goal: 
- 在 g0v Summit 曝光後，能夠吸引使用者用 sense.tw
    - unique PV > 200 => user 372
    - 註冊數 > 20 => 25
    - > 1 new map => 1
- 知道 g0v Summit campaign 成效 => not organized tracking report on event

### 曝光
活動：
- [x] Roundtable @ael（10/1 簡報 review，1）#293
- [x] lightning talk（可以用 sense.tw 整理某場 roundtable 的內容，1）雅鈞/宏宏

內容：
- [ ] 10/4 Landing page in English and Chinese @ael (1) #294 
- [x] 10/2 Demo maps: g0v 黑客松議題整理 @雅鈞(3)、無人機、網路中立性（宏宏？2）#172

技術：10/5
- SEO setting(https://github.com/SenseTW/sensetw/issues/287) @caasi(1)
- sense.tw 瀏覽器 header 放上 sense 的 logo @caasi #286 
- og title, image, description（之後 caasi 再拆），先做全站的 og title, image, description @caasi(0.5)
- !!Tracking GTM： 9/27 @ael (2.5) #256,10/4 @caasi(?) research #288
    - userid, log-in status in data layer
    - cross device and cross sub-domain tracking： api, via, sensemap

**Comment by aelcenganda** [comment]
add result
