### ISSUE TITLE
m18 sprint checkpoint

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#388]
- [ ] 用 project 設定 outcomes. (12/4)
- [x] 跟凱蘭對產品 service blueprint (12/7)、journey map  (#371)  (12/14)
- [x] 跟小班單據編列成冊進度 (12/6) - re-assigned to singing
- [x] 跟 ael 對 blog 搬到 medium #390 (12/11)
- [x] 跟 ael 對文件 #391 (12/7)、 #387 (12/7)
-  [x] 跟 ael , lloyd 對人事離退進度。 (12/06)
- [x] 跟 lloyd 對議題小聚操作方式 #375 (12/11)
- [x] 跟卡西對 frontend 文件撰寫進度 (12/7）
- [x] 跟卡西對 type unit test  #395 (12/14)
- [ ] 跟 yenwen 對cloud reduce cost的狀態 （12/11）
- [ ] 報告 1 填肉 (breakdown tasks) 12/11  對 #285
- [ ] 報告 2 大綱定稿 (breakdown tasks)  12/11  對 #290
